"""empty message

Revision ID: 405c746dba82
Revises: 6ff0154e82ac
Create Date: 2024-07-24 16:11:03.705361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405c746dba82'
down_revision = '6ff0154e82ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('borrowed')

    # ### end Alembic commands ###
