"""empty message

Revision ID: 6ff0154e82ac
Revises: f62c71496309
Create Date: 2024-07-24 16:10:46.750482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff0154e82ac'
down_revision = 'f62c71496309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('borrowed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
