"""empty message

Revision ID: f62c71496309
Revises: b08a801c7685
Create Date: 2024-07-24 16:10:15.845552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62c71496309'
down_revision = 'b08a801c7685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed', sa.Boolean(), nullable=True))
        batch_op.drop_column('burrowed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burrowed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('borrowed')

    # ### end Alembic commands ###
